// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error ListQueues, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "fwlink", Scope = "member", Target = "AcmeCorp.AspNetBuildSample.Web.UI.Filters.InitializeSimpleMembershipAttribute+SimpleMembershipInitializer.#.ctor()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "LinkId", Scope = "member", Target = "AcmeCorp.AspNetBuildSample.Web.UI.Filters.InitializeSimpleMembershipAttribute+SimpleMembershipInitializer.#.ctor()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "AcmeCorp.AspNetBuildSample.Web.UI.MvcApplication.#Application_Start()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1812:AvoidUninstantiatedInternalClasses", Scope = "type", Target = "AcmeCorp.AspNetBuildSample.Web.UI.Filters.InitializeSimpleMembershipAttribute+SimpleMembershipInitializer")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Login", Scope = "type", Target = "AcmeCorp.AspNetBuildSample.Web.UI.Models.RegisterExternalLoginModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Login", Scope = "type", Target = "AcmeCorp.AspNetBuildSample.Web.UI.Models.LoginModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Login", Scope = "type", Target = "AcmeCorp.AspNetBuildSample.Web.UI.Models.ExternalLogin")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Login", Scope = "member", Target = "AcmeCorp.AspNetBuildSample.Web.UI.Models.RegisterExternalLoginModel.#ExternalLoginData")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Login", Scope = "member", Target = "AcmeCorp.AspNetBuildSample.Web.UI.Controllers.ManageMessageId.#RemoveLoginSuccess")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Login", Scope = "member", Target = "AcmeCorp.AspNetBuildSample.Web.UI.Controllers.AccountController.#Login(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Login", Scope = "member", Target = "AcmeCorp.AspNetBuildSample.Web.UI.Controllers.AccountController.#Login(AcmeCorp.AspNetBuildSample.Web.UI.Models.LoginModel,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Login", Scope = "member", Target = "AcmeCorp.AspNetBuildSample.Web.UI.Controllers.AccountController.#ExternalLoginFailure()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Login", Scope = "member", Target = "AcmeCorp.AspNetBuildSample.Web.UI.Controllers.AccountController.#ExternalLoginConfirmation(AcmeCorp.AspNetBuildSample.Web.UI.Models.RegisterExternalLoginModel,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Login", Scope = "member", Target = "AcmeCorp.AspNetBuildSample.Web.UI.Controllers.AccountController.#ExternalLogin(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Login", Scope = "member", Target = "AcmeCorp.AspNetBuildSample.Web.UI.Controllers.AccountController.#ExternalLoginCallback(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "AcmeCorp.AspNetBuildSample.Web.UI.WebApiConfig.#Register(System.Web.Http.HttpConfiguration)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "AcmeCorp.AspNetBuildSample.Web.UI.FilterConfig.#RegisterGlobalFilters(System.Web.Mvc.GlobalFilterCollection)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "AcmeCorp.AspNetBuildSample.Web.UI.BundleConfig.#RegisterBundles(System.Web.Optimization.BundleCollection)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "AcmeCorp.AspNetBuildSample.Web.UI.Controllers.AccountController.#Register(AcmeCorp.AspNetBuildSample.Web.UI.Models.RegisterModel)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "AcmeCorp.AspNetBuildSample.Web.UI.Controllers.AccountController.#Manage(AcmeCorp.AspNetBuildSample.Web.UI.Models.LocalPasswordModel)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "AcmeCorp.AspNetBuildSample.Web.UI.Controllers.AccountController.#Login(AcmeCorp.AspNetBuildSample.Web.UI.Models.LoginModel,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "0#", Scope = "member", Target = "AcmeCorp.AspNetBuildSample.Web.UI.Controllers.AccountController.#Login(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "1#", Scope = "member", Target = "AcmeCorp.AspNetBuildSample.Web.UI.Controllers.AccountController.#Login(AcmeCorp.AspNetBuildSample.Web.UI.Models.LoginModel,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "0#", Scope = "member", Target = "AcmeCorp.AspNetBuildSample.Web.UI.Controllers.AccountController.#ExternalLoginsList(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "1#", Scope = "member", Target = "AcmeCorp.AspNetBuildSample.Web.UI.Controllers.AccountController.#ExternalLoginConfirmation(AcmeCorp.AspNetBuildSample.Web.UI.Models.RegisterExternalLoginModel,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "0#", Scope = "member", Target = "AcmeCorp.AspNetBuildSample.Web.UI.Controllers.AccountController.#ExternalLoginCallback(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "1#", Scope = "member", Target = "AcmeCorp.AspNetBuildSample.Web.UI.Controllers.AccountController.#ExternalLogin(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1053:StaticHolderTypesShouldNotHaveConstructors", Scope = "type", Target = "AcmeCorp.AspNetBuildSample.Web.UI.RouteConfig")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1053:StaticHolderTypesShouldNotHaveConstructors", Scope = "type", Target = "AcmeCorp.AspNetBuildSample.Web.UI.FilterConfig")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1053:StaticHolderTypesShouldNotHaveConstructors", Scope = "type", Target = "AcmeCorp.AspNetBuildSample.Web.UI.BundleConfig")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "AcmeCorp.AspNetBuildSample.Web.UI.Controllers.AccountController.#Manage(AcmeCorp.AspNetBuildSample.Web.UI.Models.LocalPasswordModel)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "AcmeCorp.AspNetBuildSample.Web.UI.Filters")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "AcmeCorp.AspNetBuildSample.Web.UI.Controllers")]
